# Generated by Django 3.2.10 on 2024-11-17 20:30

from django.db import migrations
from phonenumbers import is_valid_number, parse


def get_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats.iterator():
        pure_phone = parse(flat.owners_phonenumber, 'RU')
        if is_valid_number(pure_phone):
            flat.pure_phone = pure_phone
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        flat.pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20241117_2236'),
    ]

    operations = [
        migrations.RunPython(get_pure_phone, move_backward)
    ]
