# Generated by Django 3.2.10 on 2024-11-17 20:30

from django.db import migrations
from phonenumbers import is_valid_number, parse


def get_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        owner_pure_phone = parse(flat.owners_phonenumber, 'RU')
        if is_valid_number(owner_pure_phone):
            flat.owner_pure_phone = owner_pure_phone
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20241117_2236'),
    ]

    operations = [
        migrations.RunPython(get_owner_pure_phone, move_backward)
    ]
