# Generated by Django 3.2.10 on 2024-11-17 20:30

from django.db import migrations
from phonenumber_field.phonenumber import PhoneNumber
from phonenumbers import is_valid_number, parse


def get_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        phonenumber = flat.owners_phonenumber
        if is_valid_number(parse(phonenumber, 'RU')):
            flat.owner_pure_phone = PhoneNumber.from_string(phonenumber, region='RU')
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(owner_pure_phone=0)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20241117_2236'),
    ]

    operations = [
        migrations.RunPython(get_owner_pure_phone, move_backward)
    ]
