# Generated by Django 3.2.10 on 2024-12-03 15:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20241117_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owners_phonenumber',
            new_name='owner_phonenumber',
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('owner_phonenumber', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, verbose_name='Нормализированный номер владельца')),
                ('flats', models.ManyToManyField(db_index=True, related_name='owner_apartments', to='property.Flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
