# Generated by Django 3.2.10 on 2024-11-19 15:10

from django.db import migrations


def get_owners(apps, schemaeditor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(
            name=flat.owner,
            defaults={
                'pure_phone': flat.pure_phone,
                'phonenumber': flat.phonenumber
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20241203_1844'),
    ]

    operations = [
        migrations.RunPython(get_owners)
    ]
