# Generated by Django 3.2.10 on 2024-11-23 15:21

from django.db import migrations


def move_owners_apartments(apps, schea_editor):  # переназвать функцию
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all():
        owner.flats.set(Flat.objects.filter(owner=owner.name, owner_pure_phone=owner.owner_pure_phone))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20241203_1844'),
    ]

    operations = [
        migrations.RunPython(move_owners_apartments)
    ]