# Generated by Django 3.2.10 on 2025-02-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20241203_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
